[package]
name = "Chessbot5"
version = "0.1.0"
authors = ["SteinarSi <steinar.simonnes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asciis = "0.1.3"
